/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Time2Learn;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Dee Dee Gtz
 */
public class Dificil extends javax.swing.JFrame {

    public Dificil() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Difficult Level");        
        
        String RutaImagenes = "C:/Time 2 Learn/src/Imagenes/";
        
        ImageIcon Adivinanzas = new ImageIcon(RutaImagenes + "Adivinanzas.png");
        Icon ImageAdivinanzas = new ImageIcon(Adivinanzas.getImage().getScaledInstance(lblAdivinanzas.getWidth(), lblAdivinanzas.getHeight(), Image.SCALE_DEFAULT));
        lblAdivinanzas.setIcon(ImageAdivinanzas);
        
        ImageIcon Prefesiones = new ImageIcon(RutaImagenes + "Profesiones.png");
        Icon ImagePrefesiones = new ImageIcon(Prefesiones.getImage().getScaledInstance(lblProfesiones.getWidth(), lblProfesiones.getHeight(), Image.SCALE_DEFAULT));
        lblProfesiones.setIcon(ImagePrefesiones);
        
        ImageIcon Sentidos = new ImageIcon(RutaImagenes + "5Sentidos.png");
        Icon ImageSentidos = new ImageIcon(Sentidos.getImage().getScaledInstance(lbl5Sentidos.getWidth(), lbl5Sentidos.getHeight(), Image.SCALE_DEFAULT));
        lbl5Sentidos.setIcon(ImageSentidos);
        
        ImageIcon Emociones = new ImageIcon(RutaImagenes + "Emociones.png");
        Icon ImageEmociones = new ImageIcon(Emociones.getImage().getScaledInstance(lblEmociones.getWidth(), lblEmociones.getHeight(), Image.SCALE_DEFAULT));
        lblEmociones.setIcon(ImageEmociones);
        
        ImageIcon SistemaSolar = new ImageIcon(RutaImagenes + "SistemaSolar.png");
        Icon ImageSistemaSolar = new ImageIcon(SistemaSolar.getImage().getScaledInstance(lblSistemaSolar.getWidth(), lblSistemaSolar.getHeight(), Image.SCALE_DEFAULT));
        lblSistemaSolar.setIcon(ImageSistemaSolar);
        
        ImageIcon Meses = new ImageIcon(RutaImagenes + "Meses.png");
        Icon ImageMeses = new ImageIcon(Meses.getImage().getScaledInstance(lblMeses.getWidth(), lblMeses.getHeight(), Image.SCALE_DEFAULT));
        lblMeses.setIcon(ImageMeses);
        
        ImageIcon Menu = new ImageIcon(RutaImagenes + "Icono_Menu.png");
        Icon ImageMenu = new ImageIcon(Menu.getImage().getScaledInstance(lblCerrar1.getWidth(), lblCerrar1.getHeight(), Image.SCALE_DEFAULT));
        lblCerrar1.setIcon(ImageMenu);
        
        ImageIcon Nivel = new ImageIcon(RutaImagenes + "Nivel Dificil.png");
        Icon ImageNivel = new ImageIcon(Nivel.getImage().getScaledInstance(lblNivel.getWidth(), lblNivel.getHeight(), Image.SCALE_DEFAULT));
        lblNivel.setIcon(ImageNivel);
        
        //Imagen de Cerrar
        ImageIcon Cerrar = new ImageIcon(RutaImagenes + "Icono_Cerrar.png");
        Icon ImageCerrar = new ImageIcon(Cerrar.getImage().getScaledInstance(lblCerrar.getWidth(), lblCerrar.getHeight(), Image.SCALE_DEFAULT));
        lblCerrar.setIcon(ImageCerrar);
        
        //Imagen de Minimizar
        ImageIcon Minimizar = new ImageIcon(RutaImagenes + "Icono_Minimizar.png");
        Icon ImageMinimizar = new ImageIcon(Minimizar.getImage().getScaledInstance(lblMinimizar.getWidth(), lblMinimizar.getHeight(), Image.SCALE_DEFAULT));
        lblMinimizar.setIcon(ImageMinimizar);
        
        //Icono
        setIconImage(Toolkit.getDefaultToolkit().getImage(RutaImagenes + "Icono.png"));
        /*
        ImageIcon Numeros = new ImageIcon(ruta + "Numeros.png");
        Icon Numeros1 = new ImageIcon(Numeros.getImage().getScaledInstance(lblRopa.getWidth(), lblRopa.getHeight(), Image.SCALE_DEFAULT));
        lblRopa.setIcon(Numeros1);*/
    }
    public void lanzarSplash(){ 
        SplashSalir S = new SplashSalir();
        S.setVisible(true);
        
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialogo = new javax.swing.JDialog();
        lblNo = new javax.swing.JLabel();
        lblSi = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblAdivinanzas = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblProfesiones = new javax.swing.JLabel();
        lblCerrar1 = new javax.swing.JLabel();
        lbl5Sentidos = new javax.swing.JLabel();
        lblEmociones = new javax.swing.JLabel();
        lblSistemaSolar = new javax.swing.JLabel();
        lblMeses = new javax.swing.JLabel();

        Dialogo.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Dialogo.setAlwaysOnTop(true);
        Dialogo.setModalExclusionType(null);
        Dialogo.setUndecorated(true);
        Dialogo.setResizable(false);
        Dialogo.setType(java.awt.Window.Type.POPUP);
        Dialogo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNoMouseClicked(evt);
            }
        });
        Dialogo.getContentPane().add(lblNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 60, 40));

        lblSi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSiMouseClicked(evt);
            }
        });
        Dialogo.getContentPane().add(lblSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 60, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mensaje_Salir.png"))); // NOI18N
        Dialogo.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        lblAdivinanzas.setText("Riddle");
        lblAdivinanzas.setToolTipText("");
        lblAdivinanzas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAdivinanzas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdivinanzasMouseClicked(evt);
            }
        });

        lblNivel.setText("Nivel Dificil");
        lblNivel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNivelMouseClicked(evt);
            }
        });

        lblCerrar.setText("Cerrar");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        lblMinimizar.setText("Minimizar");
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });

        lblProfesiones.setText("Professions");
        lblProfesiones.setToolTipText("");
        lblProfesiones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblProfesiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProfesionesMouseClicked(evt);
            }
        });

        lblCerrar1.setText("Menu");
        lblCerrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrar1MouseClicked(evt);
            }
        });

        lbl5Sentidos.setText("5 Sentidos");
        lbl5Sentidos.setToolTipText("");
        lbl5Sentidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl5Sentidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl5SentidosMouseClicked(evt);
            }
        });

        lblEmociones.setText("Emoicones");
        lblEmociones.setToolTipText("");
        lblEmociones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEmociones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmocionesMouseClicked(evt);
            }
        });

        lblSistemaSolar.setText("Sistema Solar");
        lblSistemaSolar.setToolTipText("");
        lblSistemaSolar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSistemaSolar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSistemaSolarMouseClicked(evt);
            }
        });

        lblMeses.setText("Meses");
        lblMeses.setToolTipText("");
        lblMeses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMeses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMesesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblCerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(398, 398, 398)
                .addComponent(lblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244)
                .addComponent(lblMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(408, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEmociones, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(lblSistemaSolar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(lblMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAdivinanzas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(lblProfesiones, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(lbl5Sentidos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(688, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblAdivinanzas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblProfesiones, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl5Sentidos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblEmociones, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSistemaSolar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(481, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 1720, 1180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMesesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMesesMouseClicked
        Meses v = new Meses();
        v.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_lblMesesMouseClicked

    private void lblSistemaSolarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSistemaSolarMouseClicked
        SistemaSolar v = new SistemaSolar();
        v.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_lblSistemaSolarMouseClicked

    private void lblEmocionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmocionesMouseClicked
        Emociones_1 v = new Emociones_1();
        v.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_lblEmocionesMouseClicked

    private void lbl5SentidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl5SentidosMouseClicked
        Cinco_Sentidos_Juego v = new Cinco_Sentidos_Juego();
        v.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_lbl5SentidosMouseClicked

    private void lblCerrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrar1MouseClicked
        Niveles n = new Niveles();
        n.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_lblCerrar1MouseClicked

    private void lblProfesionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProfesionesMouseClicked
        Profesiones v = new Profesiones();
        v.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_lblProfesionesMouseClicked

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        Dialogo.setSize(576, 259);
        Dialogo.setLocationRelativeTo(null);
        Dialogo.setVisible(true);
        Dialogo.setBackground(new Color (0, 0, 0, 0));
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblNivelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNivelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNivelMouseClicked

    private void lblAdivinanzasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdivinanzasMouseClicked
        Adivinanza1 A = new Adivinanza1();
        A.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_lblAdivinanzasMouseClicked

    private void lblNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNoMouseClicked
        Dialogo.dispose();
    }//GEN-LAST:event_lblNoMouseClicked

    private void lblSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSiMouseClicked
        SplashSalir v = new SplashSalir();
        v.setVisible(true);

        Dialogo.dispose();
        this.dispose();
    }//GEN-LAST:event_lblSiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dificil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialogo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl5Sentidos;
    private javax.swing.JLabel lblAdivinanzas;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblCerrar1;
    private javax.swing.JLabel lblEmociones;
    private javax.swing.JLabel lblMeses;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblProfesiones;
    private javax.swing.JLabel lblSi;
    private javax.swing.JLabel lblSistemaSolar;
    // End of variables declaration//GEN-END:variables
}
