/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Time2Learn;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dee Dee Gtz
 */
public class Estaciones extends javax.swing.JFrame {
    String RutaImagenes = "C:/Time 2 Learn/src/Imagenes/";

    public Estaciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Seasons of Year");   
        
        lblVerano1.setVisible(false);
        lblPrimavera1.setVisible(false);
        lblOtoño1.setVisible(false);
        lblInvierno1.setVisible(false);
        
        ImageIcon Verano = new ImageIcon(RutaImagenes + "Estaciones_Verano1.png");
        Icon ImageVerano = new ImageIcon(Verano.getImage().getScaledInstance(lblVerano.getWidth(), lblVerano.getHeight(), Image.SCALE_DEFAULT));
        lblVerano.setIcon(ImageVerano);
        
        ImageIcon Verano2 = new ImageIcon(RutaImagenes + "Estaciones_Verano2.jpg");
        Icon ImageVerano2 = new ImageIcon(Verano2.getImage().getScaledInstance(lblVerano1.getWidth(), lblVerano1.getHeight(), Image.SCALE_DEFAULT));
        lblVerano1.setIcon(ImageVerano2);
       
        ImageIcon Primavera = new ImageIcon(RutaImagenes + "Estaciones_Primavera1.png");
        Icon ImagePrimavera = new ImageIcon(Primavera.getImage().getScaledInstance(lblPrimavera.getWidth(), lblPrimavera.getHeight(), Image.SCALE_DEFAULT));
        lblPrimavera.setIcon(ImagePrimavera);
        
        ImageIcon Primavera2 = new ImageIcon(RutaImagenes + "Estaciones_Primavera2.jpg");
        Icon ImagePrimavera2 = new ImageIcon(Primavera2.getImage().getScaledInstance(lblPrimavera1.getWidth(), lblPrimavera1.getHeight(), Image.SCALE_DEFAULT));
        lblPrimavera1.setIcon(ImagePrimavera2);
        
        ImageIcon Otoño = new ImageIcon(RutaImagenes + "Estaciones_Otoño1.png");
        Icon ImageOtoño = new ImageIcon(Otoño.getImage().getScaledInstance(lblOtoño.getWidth(), lblOtoño.getHeight(), Image.SCALE_DEFAULT));
        lblOtoño.setIcon(ImageOtoño);
        
        ImageIcon Otoño2 = new ImageIcon(RutaImagenes + "Estaciones_Otoño2.jpg");
        Icon ImageOtoño2 = new ImageIcon(Otoño2.getImage().getScaledInstance(lblOtoño1.getWidth(), lblOtoño1.getHeight(), Image.SCALE_DEFAULT));
        lblOtoño1.setIcon(ImageOtoño2);
        
        ImageIcon Invierno = new ImageIcon(RutaImagenes + "Estaciones_Invierno1.png");
        Icon ImageInvierno = new ImageIcon(Invierno.getImage().getScaledInstance(lblInvierno.getWidth(), lblInvierno.getHeight(), Image.SCALE_DEFAULT));
        lblInvierno.setIcon(ImageInvierno);
        
        ImageIcon Invierno2 = new ImageIcon(RutaImagenes + "Estaciones_Invierno2.jpg");
        Icon ImageInvierno2 = new ImageIcon(Invierno2.getImage().getScaledInstance(lblInvierno1.getWidth(), lblInvierno1.getHeight(), Image.SCALE_DEFAULT));
        lblInvierno1.setIcon(ImageInvierno2);
        
        ImageIcon Estaciones = new ImageIcon(RutaImagenes + "Estaciones.png");
        Icon ImageEstaciones = new ImageIcon(Estaciones.getImage().getScaledInstance(lblEstaciones.getWidth(), lblEstaciones.getHeight(), Image.SCALE_DEFAULT));
        lblEstaciones.setIcon(ImageEstaciones);
        
        ImageIcon Menu = new ImageIcon(RutaImagenes + "Icono_Menu.png");
        Icon ImageMenu = new ImageIcon(Menu.getImage().getScaledInstance(lblMenu.getWidth(), lblMenu.getHeight(), Image.SCALE_DEFAULT));
        lblMenu.setIcon(ImageMenu);
        //Imagen de Minimizar
        ImageIcon Minimizar = new ImageIcon(RutaImagenes + "Icono_Minimizar.png");
        Icon ImageMinimizar = new ImageIcon(Minimizar.getImage().getScaledInstance(lblMinimizar.getWidth(), lblMinimizar.getHeight(), Image.SCALE_DEFAULT));
        lblMinimizar.setIcon(ImageMinimizar);
        
        //Imagen de Cerrar
        ImageIcon Cerrar = new ImageIcon(RutaImagenes + "Icono_Cerrar.png");
        Icon ImageCerrar = new ImageIcon(Cerrar.getImage().getScaledInstance(lblCerrar.getWidth(), lblCerrar.getHeight(), Image.SCALE_DEFAULT));
        lblCerrar.setIcon(ImageCerrar);
        
        //Icono de Cerrar
        setIconImage(Toolkit.getDefaultToolkit().getImage(RutaImagenes + "Icono.png"));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialogo = new javax.swing.JDialog();
        lblNo = new javax.swing.JLabel();
        lblSi = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblVerano = new javax.swing.JLabel();
        lblVerano1 = new javax.swing.JLabel();
        lblPrimavera = new javax.swing.JLabel();
        lblPrimavera1 = new javax.swing.JLabel();
        lblOtoño = new javax.swing.JLabel();
        lblOtoño1 = new javax.swing.JLabel();
        lblInvierno = new javax.swing.JLabel();
        lblInvierno1 = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        lblEstaciones = new javax.swing.JLabel();
        lblEstaciones1 = new javax.swing.JLabel();

        Dialogo.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Dialogo.setAlwaysOnTop(true);
        Dialogo.setModalExclusionType(null);
        Dialogo.setUndecorated(true);
        Dialogo.setResizable(false);
        Dialogo.setType(java.awt.Window.Type.POPUP);
        Dialogo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNoMouseClicked(evt);
            }
        });
        Dialogo.getContentPane().add(lblNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 60, 40));

        lblSi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSiMouseClicked(evt);
            }
        });
        Dialogo.getContentPane().add(lblSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 60, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mensaje_Salir.png"))); // NOI18N
        Dialogo.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblVerano.setText("jLabel1");
        lblVerano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVerano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVeranoMouseClicked(evt);
            }
        });

        lblVerano1.setText("jLabel1");
        lblVerano1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblPrimavera.setText("jLabel1");
        lblPrimavera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPrimavera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrimaveraMouseClicked(evt);
            }
        });

        lblPrimavera1.setText("jLabel1");
        lblPrimavera1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPrimavera1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrimavera1MouseClicked(evt);
            }
        });

        lblOtoño.setText("jLabel1");
        lblOtoño.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOtoño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOtoñoMouseClicked(evt);
            }
        });

        lblOtoño1.setText("jLabel1");
        lblOtoño1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOtoño1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOtoño1MouseClicked(evt);
            }
        });

        lblInvierno.setText("jLabel1");
        lblInvierno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInvierno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInviernoMouseClicked(evt);
            }
        });

        lblInvierno1.setText("jLabel1");
        lblInvierno1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInvierno1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInvierno1MouseClicked(evt);
            }
        });

        lblMenu.setText("Menu");
        lblMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
        });

        lblMinimizar.setText("Minimizar");
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });

        lblCerrar.setText("Cerrar");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        lblEstaciones.setText("Estaciones");

        lblEstaciones1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblEstaciones1.setText("<html><body><p align='center'>Select a season of the year and discover how it looks.</p></body></html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(420, 420, 420)
                .addComponent(lblEstaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                .addComponent(lblMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(417, 417, 417))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblVerano, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(lblVerano1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPrimavera, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(lblPrimavera1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblInvierno, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(lblInvierno1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblOtoño, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(lblOtoño1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(lblEstaciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblEstaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEstaciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVerano, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVerano1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOtoño, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOtoño1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimavera, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrimavera1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInvierno, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInvierno1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblVeranoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVeranoMouseClicked
        lblVerano1.setVisible(true);
    }//GEN-LAST:event_lblVeranoMouseClicked

    private void lblPrimaveraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrimaveraMouseClicked
        lblPrimavera1.setVisible(true);
    }//GEN-LAST:event_lblPrimaveraMouseClicked

    private void lblPrimavera1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrimavera1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPrimavera1MouseClicked

    private void lblOtoñoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOtoñoMouseClicked
        lblOtoño1.setVisible(true);
    }//GEN-LAST:event_lblOtoñoMouseClicked

    private void lblOtoño1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOtoño1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOtoño1MouseClicked

    private void lblInviernoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInviernoMouseClicked
        lblInvierno1.setVisible(true);
    }//GEN-LAST:event_lblInviernoMouseClicked

    private void lblInvierno1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInvierno1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblInvierno1MouseClicked

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked
        //Nivel donde esta el juego
        Intermedio D = new Intermedio();
        D.setVisible(true);

        this.dispose();
    
    }//GEN-LAST:event_lblMenuMouseClicked

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        Dialogo.setSize(576, 259);
        Dialogo.setLocationRelativeTo(null);
        Dialogo.setVisible(true);
        Dialogo.setBackground(new Color (0, 0, 0, 0));
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNoMouseClicked
        Dialogo.dispose();
    }//GEN-LAST:event_lblNoMouseClicked

    private void lblSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSiMouseClicked
        SplashSalir v = new SplashSalir();
        v.setVisible(true);

        Dialogo.dispose();
        this.dispose();
    }//GEN-LAST:event_lblSiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialogo;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblEstaciones;
    private javax.swing.JLabel lblEstaciones1;
    private javax.swing.JLabel lblInvierno;
    private javax.swing.JLabel lblInvierno1;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblOtoño;
    private javax.swing.JLabel lblOtoño1;
    private javax.swing.JLabel lblPrimavera;
    private javax.swing.JLabel lblPrimavera1;
    private javax.swing.JLabel lblSi;
    private javax.swing.JLabel lblVerano;
    private javax.swing.JLabel lblVerano1;
    // End of variables declaration//GEN-END:variables
}

