/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Time2Learn;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dee Dee Gtz
 */
public class Facil extends javax.swing.JFrame {

   public Facil() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Levels");        
        
        String RutaImagenes = "C:/Time 2 Learn/src/Imagenes/";
        
        ImageIcon Menu = new ImageIcon(RutaImagenes + "Icono_Menu.png");
        Icon ImageMenu = new ImageIcon(Menu.getImage().getScaledInstance(lblMenu.getWidth(), lblMenu.getHeight(), Image.SCALE_DEFAULT));
        lblMenu.setIcon(ImageMenu);
        
        ImageIcon ABC = new ImageIcon(RutaImagenes + "ABC.png");
        Icon ABC1 = new ImageIcon(ABC.getImage().getScaledInstance(lblABC.getWidth(), lblABC.getHeight(), Image.SCALE_DEFAULT));
        lblABC.setIcon(ABC1);
        
        ImageIcon Colores = new ImageIcon(RutaImagenes + "Colores.png");
        Icon Colores1 = new ImageIcon(Colores.getImage().getScaledInstance(lblColores.getWidth(), lblColores.getHeight(), Image.SCALE_DEFAULT));
        lblColores.setIcon(Colores1);
        
        ImageIcon Animales = new ImageIcon(RutaImagenes + "Animales.png");
        Icon Animales1 = new ImageIcon(Animales.getImage().getScaledInstance(lblAnimales.getWidth(), lblAnimales.getHeight(), Image.SCALE_DEFAULT));
        lblAnimales.setIcon(Animales1);
        
        ImageIcon Numeros = new ImageIcon(RutaImagenes + "Numeros.png");
        Icon Numeros1 = new ImageIcon(Numeros.getImage().getScaledInstance(lblNumeros.getWidth(), lblNumeros.getHeight(), Image.SCALE_DEFAULT));
        lblNumeros.setIcon(Numeros1);
        
        ImageIcon Instrumentos = new ImageIcon(RutaImagenes + "Instrumentos.png");
        Icon Instrumentos1 = new ImageIcon(Instrumentos.getImage().getScaledInstance(lblInstrumentos.getWidth(), lblInstrumentos.getHeight(), Image.SCALE_DEFAULT));
        lblInstrumentos.setIcon(Instrumentos1);
        
        ImageIcon Utiles = new ImageIcon(RutaImagenes + "Utiles.png");
        Icon Utiles1 = new ImageIcon(Utiles.getImage().getScaledInstance(lblUtiles.getWidth(), lblUtiles.getHeight(), Image.SCALE_DEFAULT));
        lblUtiles.setIcon(Utiles1);
        
        ImageIcon Deportes = new ImageIcon(RutaImagenes + "Deportes.png");
        Icon Deportes1 = new ImageIcon(Deportes.getImage().getScaledInstance(lblDeportes.getWidth(), lblDeportes.getHeight(), Image.SCALE_DEFAULT));
        lblDeportes.setIcon(Deportes1);
        
        ImageIcon Transportes = new ImageIcon(RutaImagenes + "Transporte.png");
        Icon Transportes1 = new ImageIcon(Transportes.getImage().getScaledInstance(lblTransportes.getWidth(), lblTransportes.getHeight(), Image.SCALE_DEFAULT));
        lblTransportes.setIcon(Transportes1);
        
        ImageIcon Comida = new ImageIcon(RutaImagenes + "Comida.png");
        Icon Comida1 = new ImageIcon(Comida.getImage().getScaledInstance(lblComida.getWidth(), lblComida.getHeight(), Image.SCALE_DEFAULT));
        lblComida.setIcon(Comida1);
        
        ImageIcon Nivel = new ImageIcon(RutaImagenes + "Nivel Facil.png");
        Icon ImageNivel = new ImageIcon(Nivel.getImage().getScaledInstance(lblNivel.getWidth(), lblNivel.getHeight(), Image.SCALE_DEFAULT));
        lblNivel.setIcon(ImageNivel);
        
        //Imagen de Cerrar
        ImageIcon Cerrar = new ImageIcon(RutaImagenes + "Icono_Cerrar.png");
        Icon ImageCerrar = new ImageIcon(Cerrar.getImage().getScaledInstance(lblCerrar.getWidth(), lblCerrar.getHeight(), Image.SCALE_DEFAULT));
        lblCerrar.setIcon(ImageCerrar);
        
        //Imagen de Minimizar
        ImageIcon Minimizar = new ImageIcon(RutaImagenes + "Icono_Minimizar.png");
        Icon ImageMinimizar = new ImageIcon(Minimizar.getImage().getScaledInstance(lblMinimizar.getWidth(), lblMinimizar.getHeight(), Image.SCALE_DEFAULT));
        lblMinimizar.setIcon(ImageMinimizar);
        
        //Icono
        setIconImage(Toolkit.getDefaultToolkit().getImage(RutaImagenes + "Icono.png"));
    }
public void lanzarSplash(){ 
        SplashSalir S = new SplashSalir();
        S.setVisible(true);
        
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialogo = new javax.swing.JDialog();
        lblNo = new javax.swing.JLabel();
        lblSi = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblColores = new javax.swing.JLabel();
        lblAnimales = new javax.swing.JLabel();
        lblNumeros = new javax.swing.JLabel();
        lblABC = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblUtiles = new javax.swing.JLabel();
        lblDeportes = new javax.swing.JLabel();
        lblInstrumentos = new javax.swing.JLabel();
        lblTransportes = new javax.swing.JLabel();
        lblComida = new javax.swing.JLabel();

        Dialogo.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Dialogo.setAlwaysOnTop(true);
        Dialogo.setModalExclusionType(null);
        Dialogo.setUndecorated(true);
        Dialogo.setResizable(false);
        Dialogo.setType(java.awt.Window.Type.POPUP);
        Dialogo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DialogoKeyPressed(evt);
            }
        });
        Dialogo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNoMouseClicked(evt);
            }
        });
        Dialogo.getContentPane().add(lblNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 60, 40));

        lblSi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSiMouseClicked(evt);
            }
        });
        Dialogo.getContentPane().add(lblSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 60, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mensaje_Salir.png"))); // NOI18N
        Dialogo.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        lblColores.setText("Colors");
        lblColores.setToolTipText("");
        lblColores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblColores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblColoresMouseClicked(evt);
            }
        });

        lblAnimales.setText("Animals");
        lblAnimales.setToolTipText("");
        lblAnimales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnimalesMouseClicked(evt);
            }
        });

        lblNumeros.setText("Numers");
        lblNumeros.setToolTipText("");
        lblNumeros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNumeros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNumerosMouseClicked(evt);
            }
        });

        lblABC.setText("ABC");
        lblABC.setToolTipText("");
        lblABC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblABC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblABCMouseClicked(evt);
            }
        });

        lblNivel.setText("Nivel Facil");
        lblNivel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNivelMouseClicked(evt);
            }
        });

        lblCerrar.setText("jLabel1");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        lblMenu.setText("jLabel1");
        lblMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
        });

        lblMinimizar.setText("jLabel1");
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });

        lblUtiles.setText("Utiles");
        lblUtiles.setToolTipText("");
        lblUtiles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUtiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUtilesMouseClicked(evt);
            }
        });

        lblDeportes.setText("Deportes");
        lblDeportes.setToolTipText("");
        lblDeportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDeportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDeportesMouseClicked(evt);
            }
        });

        lblInstrumentos.setText("Instrumentos");
        lblInstrumentos.setToolTipText("");
        lblInstrumentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInstrumentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInstrumentosMouseClicked(evt);
            }
        });

        lblTransportes.setText("Transportes");
        lblTransportes.setToolTipText("");
        lblTransportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTransportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTransportesMouseClicked(evt);
            }
        });

        lblComida.setText("Food");
        lblComida.setToolTipText("");
        lblComida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblComida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblComidaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(395, 395, 395)
                        .addComponent(lblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(260, 260, 260)
                        .addComponent(lblMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblABC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblComida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(lblInstrumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(lblUtiles, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(lblDeportes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(lblTransportes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblColores, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(lblAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(lblNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(2523, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblColores, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblABC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblUtiles, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDeportes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTransportes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblInstrumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblComida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(455, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked
        Niveles v = new Niveles();
        v.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_lblMenuMouseClicked

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        Dialogo.setSize(576, 259);
        Dialogo.setLocationRelativeTo(null);
        Dialogo.setVisible(true);
        Dialogo.setBackground(new Color (0, 0, 0, 0));
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblNivelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNivelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNivelMouseClicked

    private void lblABCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblABCMouseClicked
        ABC A = new ABC();
        A.setVisible(true);

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_lblABCMouseClicked

    private void lblNumerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNumerosMouseClicked
        Numeros Num = new Numeros();
        Num.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_lblNumerosMouseClicked

    private void lblAnimalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnimalesMouseClicked
        Animales2 A = new Animales2();
        A.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_lblAnimalesMouseClicked

    private void lblColoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblColoresMouseClicked
        Colores C = new Colores();
        C.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_lblColoresMouseClicked

    private void lblUtilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUtilesMouseClicked
        Utiles_Inicio C = new Utiles_Inicio();
        C.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_lblUtilesMouseClicked

    private void lblDeportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeportesMouseClicked
        Deportes C = new Deportes();
        C.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_lblDeportesMouseClicked

    private void lblInstrumentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInstrumentosMouseClicked
        Instrumentos C = new Instrumentos();
        C.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_lblInstrumentosMouseClicked

    private void lblTransportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTransportesMouseClicked
        Transportes C = new Transportes();
        C.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_lblTransportesMouseClicked

    private void lblComidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComidaMouseClicked
        Comida_Comida C = new Comida_Comida();
        C.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_lblComidaMouseClicked

    private void lblNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNoMouseClicked
        Dialogo.dispose();
    }//GEN-LAST:event_lblNoMouseClicked

    private void lblSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSiMouseClicked
        SplashSalir v = new SplashSalir();
        v.setVisible(true);

        Dialogo.dispose();
        this.dispose();
    }//GEN-LAST:event_lblSiMouseClicked

    private void DialogoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DialogoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            SplashSalir v = new SplashSalir();
            v.setVisible(true);

            Dialogo.dispose();
            this.dispose();
        }
    }//GEN-LAST:event_DialogoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialogo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblABC;
    private javax.swing.JLabel lblAnimales;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblColores;
    private javax.swing.JLabel lblComida;
    private javax.swing.JLabel lblDeportes;
    private javax.swing.JLabel lblInstrumentos;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblNumeros;
    private javax.swing.JLabel lblSi;
    private javax.swing.JLabel lblTransportes;
    private javax.swing.JLabel lblUtiles;
    // End of variables declaration//GEN-END:variables
}
