/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Time2Learn;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dee Dee Gtz
 */
public class Registro extends javax.swing.JFrame {
    int n = 6;
    String RutaImagenes = "C:/Time 2 Learn/src/Imagenes/";

    public Registro() {
        initComponents();
        int n = 6;
        
        this.setTitle("Register");
            this.setExtendedState(MAXIMIZED_BOTH);
        
        //Imagen de la Niña
        ImageIcon imagenniña = new ImageIcon(RutaImagenes + "niña1.png");
        Icon icono_Niña = new ImageIcon(imagenniña.getImage().getScaledInstance(lblNiña.getWidth(), lblNiña.getHeight(),Image.SCALE_DEFAULT));
        lblNiña.setIcon(icono_Niña);
                
        //Imagen del Niño
        ImageIcon imagenniño = new ImageIcon(RutaImagenes + "niño1.png");
        Icon icono_Niño = new ImageIcon(imagenniño.getImage().getScaledInstance(lblNiño.getWidth(), lblNiño.getHeight(),Image.SCALE_DEFAULT));
        lblNiño.setIcon(icono_Niño);
        
        //Imagen de Minimizar
        ImageIcon Minimizar = new ImageIcon(RutaImagenes + "Icono_Minimizar.png");
        Icon ImageMinimizar = new ImageIcon(Minimizar.getImage().getScaledInstance(lblMinimizar.getWidth(), lblMinimizar.getHeight(), Image.SCALE_DEFAULT));
        lblMinimizar.setIcon(ImageMinimizar);
        
        //Imagen de Cerrar
        ImageIcon Cerrar = new ImageIcon(RutaImagenes + "Icono_Cerrar.png");
        Icon ImageCerrar = new ImageIcon(Cerrar.getImage().getScaledInstance(lblCerrar.getWidth(), lblCerrar.getHeight(), Image.SCALE_DEFAULT));
        lblCerrar.setIcon(ImageCerrar);
        
        //Imagen de Menos
        ImageIcon Menos = new ImageIcon(RutaImagenes + "Menos (Activo).png");
        Icon ImageMenos = new ImageIcon(Menos.getImage().getScaledInstance(lblMenos.getWidth(), lblMenos.getHeight(), Image.SCALE_DEFAULT));
        lblMenos.setIcon(ImageMenos);
        
        //Imagen de Mas
        ImageIcon Mas = new ImageIcon(RutaImagenes + "Mas (Activo).png");
        Icon ImageMas = new ImageIcon(Mas.getImage().getScaledInstance(lblMas.getWidth(), lblMas.getHeight(), Image.SCALE_DEFAULT));
        lblMas.setIcon(ImageMas);
        
        //Imagen de Continue
        ImageIcon Continue = new ImageIcon(RutaImagenes + "Continue.png");
        Icon ImageContinue = new ImageIcon(Continue.getImage().getScaledInstance(lblContinue.getWidth(), lblContinue.getHeight(), Image.SCALE_DEFAULT));
        lblContinue.setIcon(ImageContinue);
        
        //Icono
        setIconImage(Toolkit.getDefaultToolkit().getImage(RutaImagenes + "icono.png"));

        txtEdad.setText("" + n);
        lblMenos.setEnabled(false);
    }
    
    public static String Nombre, Genero2;

    
    public void lanzarSplash(){ 
        SplashSalir S = new SplashSalir();
        S.setVisible(true);
        
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Genero = new javax.swing.ButtonGroup();
        Dialogo = new javax.swing.JDialog();
        lblNo = new javax.swing.JLabel();
        lblSi = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Mensaje1 = new javax.swing.JDialog();
        NOmbre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Mensaje2 = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SelectGender = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        EnterName = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNiño = new javax.swing.JLabel();
        lblNiña = new javax.swing.JLabel();
        JRNiña = new javax.swing.JRadioButton();
        JRNiño = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        lblMinimizar = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        lblMas = new javax.swing.JLabel();
        lblMenos = new javax.swing.JLabel();
        lblContinue = new javax.swing.JLabel();

        Dialogo.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Dialogo.setAlwaysOnTop(true);
        Dialogo.setModalExclusionType(null);
        Dialogo.setUndecorated(true);
        Dialogo.setResizable(false);
        Dialogo.setType(java.awt.Window.Type.POPUP);
        Dialogo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DialogoKeyPressed(evt);
            }
        });
        Dialogo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNoMouseClicked(evt);
            }
        });
        Dialogo.getContentPane().add(lblNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 60, 40));

        lblSi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSiMouseClicked(evt);
            }
        });
        Dialogo.getContentPane().add(lblSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 60, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mensaje_Salir.png"))); // NOI18N
        Dialogo.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Mensaje1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Mensaje1.setAlwaysOnTop(true);
        Mensaje1.setModalExclusionType(null);
        Mensaje1.setUndecorated(true);
        Mensaje1.setResizable(false);
        Mensaje1.setType(java.awt.Window.Type.POPUP);
        Mensaje1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Mensaje1KeyPressed(evt);
            }
        });
        Mensaje1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NOmbre.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        NOmbre.setText(" ");
        Mensaje1.getContentPane().add(NOmbre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        Mensaje1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 50, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mensaje1.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        Mensaje1.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 120));

        Mensaje2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Mensaje2.setAlwaysOnTop(true);
        Mensaje2.setModalExclusionType(null);
        Mensaje2.setUndecorated(true);
        Mensaje2.setResizable(false);
        Mensaje2.setType(java.awt.Window.Type.POPUP);
        Mensaje2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Mensaje2KeyPressed(evt);
            }
        });
        Mensaje2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        Mensaje2.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 50, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mensaje2.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        Mensaje2.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 120));

        SelectGender.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        SelectGender.setAlwaysOnTop(true);
        SelectGender.setModalExclusionType(null);
        SelectGender.setUndecorated(true);
        SelectGender.setResizable(false);
        SelectGender.setType(java.awt.Window.Type.POPUP);
        SelectGender.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        SelectGender.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 50, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Select Gender.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        SelectGender.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 120));

        EnterName.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        EnterName.setAlwaysOnTop(true);
        EnterName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        EnterName.setModalExclusionType(null);
        EnterName.setUndecorated(true);
        EnterName.setResizable(false);
        EnterName.setType(java.awt.Window.Type.POPUP);
        EnterName.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        EnterName.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 50, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Enter Name.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        EnterName.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 120));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        JRNiña.setBackground(new java.awt.Color(255, 255, 153));
        Genero.add(JRNiña);
        JRNiña.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        JRNiña.setText("Girl");
        JRNiña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        JRNiño.setBackground(new java.awt.Color(255, 255, 153));
        Genero.add(JRNiño);
        JRNiño.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        JRNiño.setText("Boy");
        JRNiño.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Enter your age");

        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Enter your name");

        txtEdad.setEditable(false);
        txtEdad.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtEdad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEdad.setText("6");
        txtEdad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });

        lblMinimizar.setText("Minimizar");
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });

        lblCerrar.setText("Cerrar");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        lblMas.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMasMouseClicked(evt);
            }
        });

        lblMenos.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMenos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenosMouseClicked(evt);
            }
        });

        lblContinue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblContinue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContinueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblContinueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblContinueMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(544, 544, 544)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblMas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(lblNiña, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(330, 330, 330)
                                .addComponent(JRNiña)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(336, 336, 336)
                                .addComponent(lblNiño, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(480, 480, 480)
                                .addComponent(JRNiño)))
                        .addGap(123, 123, 123)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(598, 598, 598)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1174, 1174, 1174)
                        .addComponent(lblMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 930, Short.MAX_VALUE)
                .addComponent(lblContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(686, 686, 686))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNiño, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JRNiño))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNiña, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JRNiña))))
                    .addComponent(lblMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblContinue, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(126, 126, 126))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        Dialogo.setSize(576, 259);
        Dialogo.setLocationRelativeTo(null);
        Dialogo.setVisible(true);
        Dialogo.setBackground(new Color (0, 0, 0, 0));        
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblMenosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenosMouseClicked
        if (n > 6)
        {
        n = n - 1;
        
        txtEdad.setText("" + n);

        lblMas.setEnabled(true);
        
        if (n == 6)
        {
            lblMenos.setEnabled(false);
        }
        }
    }//GEN-LAST:event_lblMenosMouseClicked

    private void lblMasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMasMouseClicked
    
        if (n <= 11)
        {
        n = n + 1;
        txtEdad.setText("" + n);
            
        lblMenos.setEnabled(true);
        
        if (n == 12)
        {
            lblMas.setEnabled(false);
        }
        }
    }//GEN-LAST:event_lblMasMouseClicked

    private void lblSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSiMouseClicked
        SplashSalir v = new SplashSalir();
        v.setVisible(true);
        
        Dialogo.dispose();
        this.dispose();
    }//GEN-LAST:event_lblSiMouseClicked

    private void lblNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNoMouseClicked
        Dialogo.dispose();
    }//GEN-LAST:event_lblNoMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
            Mensaje1.dispose();
            Mensaje2.setSize(300, 120);
            Mensaje2.setLocationRelativeTo(null);
            Mensaje2.setVisible(true);
            Mensaje2.setBackground(new Color (0, 0, 0, 0));        
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Mensaje2.dispose();
        Registro.super.dispose();
        
        Niveles n = new Niveles();
        n.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void lblContinueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContinueMouseClicked
        //Imagen para Mensaje (Incorrecto)
        String RutaImagenes = "C:/Time 2 Learn/src/Imagenes/";
        
        //Incorrecto
        ImageIcon Mensaje = new ImageIcon(RutaImagenes + "incorrecto.png");
        Icon ImageMensaje = new ImageIcon(Mensaje.getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT));
        
        if ("".equals(txtEdad.getText()) || JRNiña.isSelected() == false && JRNiño.isSelected() == false || "".equals(txtNombre.getText()))
        {   
            if ("".equals(txtEdad.getText()))
            {
                JOptionPane.showMessageDialog(null, "Enter your age", "Warning!", JOptionPane.PLAIN_MESSAGE, ImageMensaje);
            }
        
            if (JRNiña.isSelected() == false && JRNiño.isSelected() == false)
            {
                SelectGender.setSize(300, 120);
                SelectGender.setLocationRelativeTo(null);
                SelectGender.setVisible(true);
                SelectGender.setBackground(new Color (0, 0, 0, 0));
            }
        
            if ("".equals(txtNombre.getText()))
            {
                EnterName.setSize(300, 120);
                EnterName.setLocationRelativeTo(null);
                EnterName.setVisible(true);
                EnterName.setBackground(new Color (0, 0, 0, 0));
            }
        }
        
        else
        {
        
        int c;
        int Edad;
        
        Nombre = String.format(txtNombre.getText());
        
        if (JRNiña.isSelected() == true)
            {Genero2 = "Niña";}
        
        else
            {Genero2 = "Niño";}
        
        Edad = Integer.parseInt(txtEdad.getText());
        
        Conexion mibasededatos = new Conexion();
        Connection con=mibasededatos.getConnection();
        Statement st, st2;
                
        String sql = "INSERT INTO registro (Nombre, Edad, Genero) VALUES ('"
                + Nombre + "','" + Edad + "','" + Genero + "');";
        
        String sql2 = "INSERT INTO puntaje (`Nombre`, `Animales`, `DiasSemana`, `Adjetivos`, `Adivinanzas`, `Profesiones`, `CincoSentidos`, `Emociones`, `Meses`, `Ropa`) VALUES ("
                +"'" + Nombre + "', '0', '0', '0', '0', '0', '0', '0', '0', '0');";
        
        try {
            st = con.createStatement();
            st2 = con.createStatement();
            
            st.executeUpdate(sql);
            st2.executeUpdate(sql2);
            
            con.close();
            st.close();
            st2.close();
           
            ImageIcon Mensaje2 = new ImageIcon(RutaImagenes + "Carita.png");
            Icon ImageMensaje2 = new ImageIcon(Mensaje2.getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT));
        
            NOmbre.setText(Nombre);
            Mensaje1.setSize(300, 120);
            Mensaje1.setLocationRelativeTo(null);
            Mensaje1.setVisible(true);
            Mensaje1.setBackground(new Color (0, 0, 0, 0));
            
                    
            
        }catch (SQLException e){
            
            System.out.println("Error en la conexion"+ sql+ "y el error es "+ e);
            JOptionPane.showMessageDialog(null, "Ha habido un error al insertar a " + Nombre  + " El error es "+ e );
        }
                
        
        }
    }//GEN-LAST:event_lblContinueMouseClicked

    private void lblContinueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContinueMouseEntered
        //Imagen de Continue2
        ImageIcon Continue2 = new ImageIcon(RutaImagenes + "Continue2.png");
        Icon ImageContinue2 = new ImageIcon(Continue2.getImage().getScaledInstance(lblContinue.getWidth(), lblContinue.getHeight(), Image.SCALE_DEFAULT));
        lblContinue.setIcon(ImageContinue2);
    }//GEN-LAST:event_lblContinueMouseEntered

    private void lblContinueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContinueMouseExited
        //Imagen de Continue
        ImageIcon Continue = new ImageIcon(RutaImagenes + "Continue.png");
        Icon ImageContinue = new ImageIcon(Continue.getImage().getScaledInstance(lblContinue.getWidth(), lblContinue.getHeight(), Image.SCALE_DEFAULT));
        lblContinue.setIcon(ImageContinue);
    }//GEN-LAST:event_lblContinueMouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        SelectGender.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        EnterName.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void Mensaje1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Mensaje1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            Mensaje1.dispose();
            
            Mensaje2.setSize(300, 120);
            Mensaje2.setLocationRelativeTo(null);
            Mensaje2.setVisible(true);
            Mensaje2.setBackground(new Color (0, 0, 0, 0));        
        }
    }//GEN-LAST:event_Mensaje1KeyPressed

    private void Mensaje2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Mensaje2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            Mensaje2.dispose();
            
            Niveles n = new Niveles();
            n.setVisible(true);
            
            this.dispose();
        }
    }//GEN-LAST:event_Mensaje2KeyPressed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_ENTER)
        {
            //Imagen para Mensaje (Incorrecto)
        String RutaImagenes = "C:/Time 2 Learn/src/Imagenes/";
        
        //Incorrecto
        ImageIcon Mensaje = new ImageIcon(RutaImagenes + "incorrecto.png");
        Icon ImageMensaje = new ImageIcon(Mensaje.getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT));
        
        if ("".equals(txtEdad.getText()) || JRNiña.isSelected() == false && JRNiño.isSelected() == false || "".equals(txtNombre.getText()))
        {   
            if ("".equals(txtEdad.getText()))
            {
                JOptionPane.showMessageDialog(null, "Enter your age", "Warning!", JOptionPane.PLAIN_MESSAGE, ImageMensaje);
            }
        
            if (JRNiña.isSelected() == false && JRNiño.isSelected() == false)
            {
                SelectGender.setSize(300, 120);
                SelectGender.setLocationRelativeTo(null);
                SelectGender.setVisible(true);
                SelectGender.setBackground(new Color (0, 0, 0, 0));
            }
        
            if ("".equals(txtNombre.getText()))
            {
                EnterName.setSize(300, 120);
                EnterName.setLocationRelativeTo(null);
                EnterName.setVisible(true);
                EnterName.setBackground(new Color (0, 0, 0, 0));
            }
        }
        
        else
        {
        
        int c;
        int Edad;
        
        Nombre = String.format(txtNombre.getText());
        
        if (JRNiña.isSelected() == true)
            {Genero2 = "Niña";}
        
        else
            {Genero2 = "Niño";}
        
        Edad = Integer.parseInt(txtEdad.getText());
        
        Conexion mibasededatos = new Conexion();
        Connection con=mibasededatos.getConnection();
        Statement st, st2;
                
        String sql = "INSERT INTO registro (Nombre, Edad, Genero) VALUES ('"
                + Nombre + "','" + Edad + "','" + Genero + "');";
        
        String sql2 = "INSERT INTO puntaje (`Nombre`, `Animales`, `DiasSemana`, `Adjetivos`, `Adivinanzas`, `Profesiones`, `CincoSentidos`, `Emociones`, `Meses`, `Ropa`) VALUES ("
                +"'" + Nombre + "', '0', '0', '0', '0', '0', '0', '0', '0', '0');";
        
        try {
            st = con.createStatement();
            st2 = con.createStatement();
            
            st.executeUpdate(sql);
            st2.executeUpdate(sql2);
            
            con.close();
            st.close();
            st2.close();
           
            ImageIcon Mensaje2 = new ImageIcon(RutaImagenes + "Carita.png");
            Icon ImageMensaje2 = new ImageIcon(Mensaje2.getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT));
        
            NOmbre.setText(Nombre);
            Mensaje1.setSize(300, 120);
            Mensaje1.setLocationRelativeTo(null);
            Mensaje1.setVisible(true);
            Mensaje1.setBackground(new Color (0, 0, 0, 0));
            
                    
            
        }catch (SQLException e){
            
            System.out.println("Error en la conexion"+ sql+ "y el error es "+ e);
            JOptionPane.showMessageDialog(null, "Ha habido un error al insertar a " + Nombre  + " El error es "+ e );
        }
        }
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void DialogoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DialogoKeyPressed
        if (evt.getKeyCode() == com.sun.glass.events.KeyEvent.VK_ENTER)
        {
            SplashSalir v = new SplashSalir();
            v.setVisible(true);

            Dialogo.dispose();
            this.dispose();
        }
    }//GEN-LAST:event_DialogoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialogo;
    private javax.swing.JDialog EnterName;
    private javax.swing.ButtonGroup Genero;
    private javax.swing.JRadioButton JRNiña;
    private javax.swing.JRadioButton JRNiño;
    private javax.swing.JDialog Mensaje1;
    private javax.swing.JDialog Mensaje2;
    private javax.swing.JLabel NOmbre;
    private javax.swing.JDialog SelectGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblContinue;
    private javax.swing.JLabel lblMas;
    private javax.swing.JLabel lblMenos;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblNiña;
    private javax.swing.JLabel lblNiño;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblSi;
    private javax.swing.JTextField txtEdad;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
